# Generated by Django 3.0.3 on 2020-06-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=35, unique=True)),
                ('nombre', models.CharField(max_length=85)),
                ('estado', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida'), ('D', 'Defectuoso')], max_length=1)),
                ('fecha_ingreso', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
